export const certifications = [
    {
        title: "Working in a Digital World: Professional Skills",
        // description: "This certification validates my expertise in designing and deploying scalable systems on AWS.",
        image: "/images/certifications/working-in-a-digital-world-professional-skills.png",
        issuer: "IBM",
        issueDate: "15 October 2025",
        credentialUrl: "https://www.credly.com/earner/earned/badge/abd456e3-e379-4b47-8c5d-5d96b6c37173",
        type: "image",
    },
    {
        title: "Cisco Support Technician Cybersecurity (CCST)",
        // description: "This certification validates my expertise in designing and deploying scalable systems on AWS.",
        image: "/images/certifications/CCST-certification.png",
        issuer: "Cisco",
        issueDate: "10 July 2025",
        credentialUrl: "https://www.credly.com/earner/earned/badge/7a029b8c-601b-4128-83a9-6ded8fdcabf6",
        type: "image",
    },
    {
        title: "Advanced Backend Programming: Python, Flask & Django",
        // description: "Validates my expertise in:\n- Advanced Python programming\n- Advanced Python programming II\n- Databases\n- Flask\n- Django\n- Testing and Optimization",
        issuer: "BeJob & IBM",
        issueDate: "09 June 2025",
        image: "/images/certifications/advanced-backend-certification.png",
        credentialUrl: "",
        type: "image",
    },
    {
        title: "Advanced Programming Technician",
        // description: "This certification validates my expertise in web development",
        issuer: "Campuslands",
        issueDate: "09 January 2025",
        image: "/images/certifications/campus-certification.png",
        credentialUrl: "",
        type: "image",
    },
    {
        title: "English Certified (C1 Advanced)",
        // description: "This certification validates my expertise in designing and deploying scalable systems on AWS.",
        image: "/images/certifications/EF CERTIFICATION.png",
        issuer: "EF SET",
        issueDate: "07 February 2025",
        credentialUrl: "https://www.youracclaim.com/badges/0987654321",
        type: "image",
    },
    {
        title: "Artificial Intelligence Fundamentals",
        // description: "This certification validates my expertise in designing and deploying scalable systems on AWS.",
        image: "/images/certifications/microsoft-security-fundamentals-certification.png",
        issuer: "Microsoft",
        issueDate: "13 March 2025",
        credentialUrl: "https://www.credly.com/badges/adc3e1ba-7a3b-4847-bd28-05410bf31e61",
        type: "image",
    },
    {
        title: "Artificial Intelligence Fundamentals",
        // description: "This certification validates my expertise in designing and deploying scalable systems on AWS.",
        image: "/images/certifications/ai-fundamentals-certification.png",
        issuer: "IBM",
        issueDate: "19 March 2025",
        credentialUrl: "https://www.credly.com/earner/earned/badge/1083779f-3df0-4e90-b075-0a578e7c52a0",
        type: "image",
    },
    {
        title: "Django: Web Development with Python",
        // description: "This certification validates my expertise in designing and deploying scalable systems on AWS.",
        image: "/images/certifications/django-certification.png",
        issuer: "Udemy",
        issueDate: "25 May 2025",
        credentialUrl: "https://www.youracclaim.com/badges/0987654321",
        type: "image",
    },
    {
        title: "English for IT 1",
        // description: "This certification validates my expertise in designing and deploying scalable systems on AWS.",
        image: "/images/certifications/english4IT-certification.png",
        issuer: "Cisco - OpenEDG",
        issueDate: "06 July 2025",
        credentialUrl: "https://www.credly.com/earner/earned/badge/20d9c48c-2411-4d09-9f8e-1d8b0d897903",
        type: "image",
    },
    {
        title: "Power BI Certification",
        // description: "This certification validates my expertise in designing and deploying scalable systems on AWS.",
        image: "/images/certifications/powerbi-certification.png",
        issuer: "EmpowerData LATAM",
        issueDate: "30 January 2025",
        credentialUrl: "https://www.youracclaim.com/badges/0987654321",
        type: "image",
    },
    {
        title: "Excel Basic Skills",
        // description: "This certification validates my expertise in designing and deploying scalable systems on AWS.",
        image: "/images/certifications/excel-certification.png",
        issuer: "EmpowerData LATAM",
        issueDate: "July 2023",
        credentialUrl: "https://www.youracclaim.com/badges/0987654321",
        type: "image",
    },
    {
        title: "IA Certification",
        // description: "This certification validates my expertise in designing and deploying scalable systems on AWS.",
        image: "/images/certifications/ia-datahack-certification.png",
        issuer: "IBM - DataHack",
        issueDate: "06 June 2025",
        credentialUrl: "https://www.youracclaim.com/badges/0987654321",
        type: "image",
    },
    {
        title: "OOP with Python",
        // description: "This certification validates my expertise in designing and deploying scalable systems on AWS.",
        image: "/images/certifications/oop-python-certification.png",
        issuer: "IBM",
        issueDate: "01 April 2025",
        credentialUrl: "https://www.youracclaim.com/badges/0987654321",
        type: "image",
    },
    {
        title: "Microsoft Certified: Azure AI Fundamentals",
        // description: "This certification validates my expertise in designing and deploying scalable systems on AWS.",
        image: "/images/certifications/azure-ai-fundamentals-certification.png",
        issuer: "Microsoft",
        issueDate: "11 April 2025",
        credentialUrl: "https://www.credly.com/earner/earned/badge/9551a57a-0e5c-49ab-912a-1c5c7d605e5f",
        type: "image",
    },

]