export const certifications = [
    {
        title: "Cisco Support Technician Cybersecurity (CCST)",
        // description: "This certification validates my expertise in designing and deploying scalable systems on AWS.",
        image: "/images/certifications/CCST-certification.png",
        issuer: "Cisco",
        issueDate: "10 July 2025",
        credentialUrl: "https://www.youracclaim.com/badges/0987654321",
        type: "image",
    },
    {
        title: "Advanced Backend Programming: Python, Flask & Django",
        // description: "Validates my expertise in:\n- Advanced Python programming\n- Advanced Python programming II\n- Databases\n- Flask\n- Django\n- Testing and Optimization",
        issuer: "BeJob & IBM",
        issueDate: "09 June 2025",
        image: "/images/certifications/advanced-backend-certification.png",
        credentialUrl: "",
        type: "image",
    },
    {
        title: "Advanced Programming Technician",
        // description: "This certification validates my expertise in web development",
        issuer: "Campuslands",
        issueDate: "09 January 2025",
        image: "/images/certifications/campus-certification.png",
        credentialUrl: "",
        type: "image",
    },
    {
        title: "English Certified (C1 Advanced)",
        // description: "This certification validates my expertise in designing and deploying scalable systems on AWS.",
        image: "/images/certifications/EF CERTIFICATION.png",
        issuer: "EF SET",
        issueDate: "07 February 2025",
        credentialUrl: "https://www.youracclaim.com/badges/0987654321",
        type: "image",
    },
    {
        title: "Django: Web Development with Python",
        // description: "This certification validates my expertise in designing and deploying scalable systems on AWS.",
        image: "/images/certifications/django-certification.png",
        issuer: "Udemy",
        issueDate: "25 May 2025",
        credentialUrl: "https://www.youracclaim.com/badges/0987654321",
        type: "image",
    },
    {
        title: "English for IT 1",
        // description: "This certification validates my expertise in designing and deploying scalable systems on AWS.",
        image: "/images/certifications/english4IT-certification.png",
        issuer: "Cisco - OpenEDG",
        issueDate: "06 July 2025",
        credentialUrl: "https://www.youracclaim.com/badges/0987654321",
        type: "image",
    },
    {
    title: "Power BI Certification",
    // description: "This certification validates my expertise in designing and deploying scalable systems on AWS.",
    image: "/images/certifications/powerbi-certification.png",
    issuer: "EmpowerData LATAM",
    issueDate: "30 January 2025",
    credentialUrl: "https://www.youracclaim.com/badges/0987654321",
    type: "image",
},
    {
        title: "Excel Basic Skills",
        // description: "This certification validates my expertise in designing and deploying scalable systems on AWS.",
        image: "/images/certifications/excel-certification.png",
        issuer: "EmpowerData LATAM",
        issueDate: "July 2023",
        credentialUrl: "https://www.youracclaim.com/badges/0987654321",
        type: "image",
    },
    {
        title: "IA Certification",
        // description: "This certification validates my expertise in designing and deploying scalable systems on AWS.",
        image: "/images/certifications/ia-datahack-certification.png",
        issuer: "IMB - DataHack",
        issueDate: "06 June 2025",
        credentialUrl: "https://www.youracclaim.com/badges/0987654321",
        type: "image",
    },
    {
        title: "OOP with Python",
        // description: "This certification validates my expertise in designing and deploying scalable systems on AWS.",
        image: "/images/certifications/oop-python-certification.png",
        issuer: "IMB",
        issueDate: "01 April 2025",
        credentialUrl: "https://www.youracclaim.com/badges/0987654321",
        type: "image",
    },

]