export const certifications = [
    {
        id: 1,
        name: "AWS Certified Solutions Architect – Associate",
        type: "image",
        issuer: "Amazon Web Services",
        issueDate: "March 2023",
        image:"images/certifications/campus-certification.png",
        credentialUrl: "https://www.youracclaim.com/badges/1234567890",
    },
    {
        id:2,
        name: "Google Cloud Professional Data Engineer",
        type: "image",
        image:"images/certifications/CCST-certification.png",
        issuer: "Google Cloud",
        issueDate: "July 2023",
        credentialUrl: "https://www.youracclaim.com/badges/0987654321",
    },
        {
        id:2,
        name: "Google Cloud Professional Data Engineer",
        type: "image",
        image:"images/certifications/CCST-certification.png",
        issuer: "Google Cloud",
        issueDate: "July 2023",
        credentialUrl: "https://www.youracclaim.com/badges/0987654321",
    },
        {
        id:2,
        name: "Google Cloud Professional Data Engineer",
        type: "image",
        image:"images/certifications/CCST-certification.png",
        issuer: "Google Cloud",
        issueDate: "July 2023",
        credentialUrl: "https://www.youracclaim.com/badges/0987654321",
    },
        {
        id:2,
        name: "Google Cloud Professional Data Engineer",
        type: "image",
        image:"images/certifications/CCST-certification.png",
        issuer: "Google Cloud",
        issueDate: "July 2023",
        credentialUrl: "https://www.youracclaim.com/badges/0987654321",
    },
        {
        id:2,
        name: "Google Cloud Professional Data Engineer",
        type: "image",
        image:"images/certifications/CCST-certification.png",
        issuer: "Google Cloud",
        issueDate: "July 2023",
        credentialUrl: "https://www.youracclaim.com/badges/0987654321",
    },
        {
        id:2,
        name: "Google Cloud Professional Data Engineer",
        type: "image",
        image:"images/certifications/CCST-certification.png",
        issuer: "Google Cloud",
        issueDate: "July 2023",
        credentialUrl: "https://www.youracclaim.com/badges/0987654321",
    },

]